name: DTAP - Mobile App (Kotlin)

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew
        working-directory: CookingGameApp

      - name: Build project
        run: ./gradlew assembleDebug
        working-directory: CookingGameApp

  static-analysis:
    name: Static Code Analysis (Detekt)
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew
        working-directory: CookingGameApp

      - name: Run Detekt
        run: ./gradlew detekt
        working-directory: CookingGameApp

  security-scan:
    name: Dependency Vulnerability Check
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew
        working-directory: CookingGameApp

      - name: Generate CycloneDX BOM
        run: ./gradlew cyclonedxBom
        working-directory: CookingGameApp